In [1]:
import pandas as pd
import numpy as np

In [6]:
pd.read_csv('../data/indoor/store_A/wifi_sessions.tsv', sep='\t')

         index  wifi_id          ts     area  dwell_time
0            0     2789  1483196428      out         139
1            1      122  1483197332      out           2
2            2     1818  1483203731      out          19
3            3      125  1483203999      out          10
4            4     5095  1483204719      out           8
5            5    16385  1483209733      out          36
6            6      973  1483231014      out         182
7            7     8319  1483232067      out         197
8            8      973  1483232109      out        1256
9            9    12905  1483232127      out         149
10          10    37785  1483232282      out          21
11          11     2047  1483232479      out         860
12          12    12907  1483232481      out         837
13          13     3001  1483233066      out          74
14          14    11910  1483233781      out         409
15          15    75474  1483233907      out          13
16          16    37785  1483234000      out          69
17          17      973  1483234534      out         255
18          18      973  1483234588     1f-c          96
19          19      973  1483234588       in         128
20          20      973  1483234588       1f         128
21          21    43831  1483235256      out          56
22          22    39919  1483235456      out         114
23          23    77117  1483235466      out          90
24          24    28686  1483235473      out          24
25          25    12912  1483235602      out         196
26          26    70303  1483235674      out          23
27          27    33126  1483235734      out          39
28          28    96522  1483235770      out        1308
29          29    49228  1483236022      out         356
...        ...      ...         ...      ...         ...
815657  926957    68725  1514722837     1f-e         154
815658  926958    68725  1514722858     1f-f         245
815659  926959    19808  1514722863       b1         782
815660  926960    99620  1514722863     1f-d        2056
815661  926961    19808  1514722884     cafe         382
815662  926962    19808  1514722900  b1_only         368
815663  926963    19808  1514722907     b1-a         353
815664  926964    52550  1514722922       in         105
815665  926965    52550  1514722922       1f         105
815666  926966    78444  1514723059     cafe         469
815667  926967    78444  1514723062     b1-b         162
815668  926968    84654  1514723159       1f         357
815669  926969    19808  1514723202     b1-c          10
815670  926970    19808  1514723230     b1-b          18
815671  926971    76905  1514723276     1f-f         227
815672  926972    84654  1514723280     1f-f         231
815673  926973    19808  1514723321     1f-d        1687
815674  926974    68725  1514723322       b1          22
815675  926975    68725  1514723323  b1_only          20
815676  926976    68725  1514723336     b1-a           6
815677  926977    19808  1514723359     1f-e        1099
815678  926981    19808  1514723558     1f-f         242
815679  926983    68725  1514723936     1f-d          38
815680  926984    68725  1514723936       1f          38
815681  926985    76905  1514724443     1f-e         120
815682  926986    76905  1514724505       b1         202
815683  926987    76905  1514724505     1f-d          29
815684  926988    76905  1514724505     1f-c         239
815685  926989    76905  1514724564  b1_only         143
815686  926990    76905  1514724652     cafe          55

[815687 rows x 5 columns]